### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by BIRD-UP73** [kira0x1/mikaela#148]
Currently the bot does not show any errors that might occur.

Suggestion
- Add a function to handle the errors in `app.ts`.
- Create a `CommandError` class, which can be thrown in commands.
- Catch the `CommandError` in `app.ts` and handle the error by sending an embed message with the error message.

**Comment by lil-kira** [comment]
<3

**Comment by BIRD-UP73** [comment]
Let's try this again using `client.on('error')` shall we?

**Comment by lil-kira** [comment]
(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by kira0x1** [comment]
Fixed
