### ISSUE TITLE
DM commands

### ISSUE THREAD

**Issue by BIRD-UP73** [kira0x1/mikaela#149]
The bot does not respond to some DM commands. Maybe send an error if a command is not allowed to be used in DMs?

**Comment by BIRD-UP73** [comment]
One thing that could be done here is add a field named `dm` to `ICommand` to indicate the command can be used in DMs. This should be set to `false` by default for backwards compatibility.

**Comment by kira0x1** [comment]
Working on this right now

**Comment by kira0x1** [comment]
Commands dont work with dm's unless they meet a certain permission. Will configure it to bot-admins later but currently its just me.
