### ISSUE TITLE
Discord user and bot permission check options

### ISSUE THREAD

**Issue by BIRD-UP73** [kira0x1/mikaela#195]
I added the following options to `ICommand`

```typescript
userPerms?: PermissionResolvable,
botPerms?: PermissionResolvable
```

Now u can add Discord permissions a user needs to run a command. For example, in the **avatar** command
```typescript
export const command: ICommand = {
    name: 'avatar',
    description: 'Shows the avatar of a user',
    aliases: ['av', 'avi', 'pfp', 'pic', 'icon', 'usericon', 'img', 'ava'],
    userPerms: ['SEND_MESSAGES'],
    botPerms: ['SEND_MESSAGES'],
```

In app.ts this check is done for both the bot and the user that tries to invoke the command.
U won't need `'SEND_MESSAGES'` because u already check for that, but this can be done with any permissions.

**Comment by kira0x1** [comment]
This is a great idea!
